# Generated by Django 3.2 on 2021-04-20 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='passing_marks',
            field=models.FloatField(default=33.3),
        ),
    ]
